# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: name-tests-test
    # Use args: ['--django'] to match test*.py instead.
    args:
    - --django
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
  - id: black
    language_version: python3.9
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
    args: ['--config', './setup.cfg']
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: ['--config-file', './setup.cfg']
- repo: local
  hooks:
  - id: prepare-commit-msg
    name: Insert issue number in commit message
    language: python
    entry: python prepare_commit_msg.py
    stages: [prepare-commit-msg]
