name: Openapi to Markdown
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install widdershins
      run: npm install -g widdershins
