name: Openapi to Markdown
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout Nodejs
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install widdershins
      run: npm install -g widdershins

    - name: Checkout Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: 'x64'

    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source ~/.poetry/env
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Cache Poetry virtualenv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('poetry.lock') }}

    - name: Install python packages
      run: |
        poetry install --no-root
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Make markdown file
      env:
        PYTHONPATH: 'apps'
      run: echo $(python -c "import json; from main import app; print(json.dumps(app.openapi()))") > doc.json
